version: "2.2"

services:
  nginx:
    build: ./nginx
    container_name: "nginx"
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
      - 8060:8060
      - 8070:8070
    cpus: NGINX_CPU_LIMIT
    mem_limit: NGINX_MEM_LIMIT
    ulimits:
      nproc: 131072
      nofile: 60000
    links:
      - "varnish"
  varnish:
    build: ./varnish
    container_name: "varnish"
    restart: unless-stopped
    expose:
      - 81
    cpus: VARNISH_CPU_LIMIT
    mem_limit: VARNISH_MEM_LIMIT
    ulimits:
      nproc: 131072
      nofile: 15726
    depends_on:
      - haproxy
  haproxy:
    build: ./haproxy
    container_name: "haproxy"
    restart: unless-stopped
    expose:
      - 82
    ports:
      - 4306:4306
      - 7379:7379
      - 9000:9000
      - 10200:10200
    cpus: HAPROXY_CPU_LIMIT
    mem_limit: HAPROXY_MEM_LIMIT
    ulimits:
      nproc: 131072
      nofile: 45000
    depends_on:
      - apache-fpm
  resque:
    build: ./resquev4
    container_name: "resque"
    restart: unless-stopped
    cpus: RESQUE_CPU_LIMIT
    mem_limit: RESQUE_MEM_LIMIT
    volumes:
      - app:/opt/qu/liveagent
    ulimits:
      nofile: 96000
    depends_on:
      - apache-fpm
  apache-fpm:
    build: ./apache-fpm
    container_name: "apache-fpm"
    restart: unless-stopped
    volumes:
      - app:/var/www/liveagent
      - /etc/geoip:/opt/geoip
      - /var/run/clamav:/var/run/clamav
    ports:
      - 800:800
    cpus: APACHE_CPU_LIMIT
    mem_limit: APACHE_MEM_LIMIT
    ulimits:
      nproc: 30240
      nofile: 65536
    depends_on:
      - mysql
      - redis
      - elasticsearch
  mysql:
    build: ./mariadb
    container_name: "mysql"
    restart: unless-stopped
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - 3306:3306
    cpus: MYSQL_CPU_LIMIT
    mem_limit: MYSQL_MEM_LIMIT
    ulimits:
      nofile: 1020000
  redis:
    build: ./redis
    container_name: "redis"
    restart: unless-stopped
    volumes:
      - redisdata:/var/lib/redis
    ports:
      - 6379:6379
    sysctls:
      - net.core.somaxconn=10000
    cpus: REDIS_CPU_LIMIT
    mem_limit: REDIS_MEM_LIMIT
    ulimits:
      nofile: 90032
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4
    container_name: elasticsearch
    restart: unless-stopped
    environment:
      - "ES_JAVA_OPTS=-XmsMIN_HEAP_SIZE -XmxMAX_HEAP_SIZE"
      - xpack.security.enabled=false
      - xpack.watcher.enabled=false
      - xpack.monitoring.enabled=false
      - bootstrap.memory_lock=true
    volumes:
      - esdata:/usr/share/elasticsearch/data
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - 9200:9200
      - 9300:9300
    cpus: ELASTIC_CPU_LIMIT
    mem_limit: ELASTIC_MEM_LIMIT
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 262144
        hard: 262144
    cap_add:
      - IPC_LOCK
volumes:
  app:
    driver: local
  dbdata:
    driver: local
  redisdata:
    driver: local
  esdata:
    driver: local
