version: "2.2"

services:
  mysql:
    build: ./mariadb
    container_name: "mysql"
    restart: unless-stopped
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - 3306:3306
    cpus: MYSQL_CPU_LIMIT
    mem_limit: MYSQL_MEM_LIMIT
    ulimits:
      nofile: 1020000
  sentinel:
    build: ./redis-sentinel
    container_name: "sentinel"
    restart: unless-stopped
    ports:
      - 26379:26379
    sysctls:
      - net.core.somaxconn=512
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4
    container_name: elasticsearch
    restart: unless-stopped
    environment:
      - "ES_JAVA_OPTS=-XmsMIN_HEAP_SIZE -XmxMAX_HEAP_SIZE"
      - xpack.security.enabled=false
      - xpack.watcher.enabled=false
      - xpack.monitoring.enabled=false
      - bootstrap.memory_lock=true
    volumes:
      - esdata:/usr/share/elasticsearch/data
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - 9200:9200
      - 9300:9300
    cpus: ELASTIC_CPU_LIMIT
    mem_limit: ELASTIC_MEM_LIMIT
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 262144
        hard: 262144
    cap_add:
      - IPC_LOCK
volumes:
  dbdata:
    driver: local
  esdata:
    driver: local
