log:
    level: notice
    path: "/var/log/resque-serial-5.log"
    application_name: "resque-v5"
    system_name: ""
    extra_prefix: ""
    context_prefix: "ctxt_"
    logstash_version: 1

redis:
    hostname: FLOAT_IP
    port: 7379

task_include_path: "/opt/qu/liveagent/"

node_id: 4_resque

allocators:
    job-count: 1
    batch-count: 1

pools:
    static:
        emails_out:
            worker_count: 4
        conversation_indexing:
            worker_count: 6
        default_job_pool:
            worker_count: 6

    batch:
        conversations_reindex:
            unit_count: 1
            workers_per_unit: 6
        default_batch_pool:
            unit_count: 1
            workers_per_unit: 6


mapping:
    static:
        default:
            default: default_job_pool
            La_Search_Jobs_ReindexTicketJob: conversation_indexing
            Gpf_Mail_Job_SendEmails: emails_out


    batch:
        default:
            default: default_batch_pool
            La_Search_Jobs_ReindexTicketJob: conversations_reindex
