version: "2.2"

services:
  nginx:
    build: ./nginx
    container_name: "nginx"
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    cpus: NGINX_CPU_LIMIT
    mem_limit: NGINX_MEM_LIMIT
    ulimits:
      nproc: 131072
      nofile: 60000
    links:
      - "varnish"
  varnish:
    build: ./varnish
    container_name: "varnish"
    restart: unless-stopped
    expose:
      - 81
    cpus: VARNISH_CPU_LIMIT
    mem_limit: VARNISH_MEM_LIMIT
    ulimits:
      nproc: 131072
      nofile: 15726
    depends_on:
      - haproxy
  haproxy:
    build: ./haproxy
    container_name: "haproxy"
    restart: unless-stopped
    expose:
      - 82
    ports:
      - 4306:4306
      - 7379:7379
      - 9000:9000
      - 10200:10200
    cpus: HAPROXY_CPU_LIMIT
    mem_limit: HAPROXY_MEM_LIMIT
    ulimits:
      nproc: 131072
      nofile: 45000
    depends_on:
      - apache-fpm
  resque:
    build: ./resquev4
    container_name: "resque"
    restart: unless-stopped
    cpus: RESQUE_CPU_LIMIT
    mem_limit: RESQUE_MEM_LIMIT
    volumes:
      - app:/opt/qu/liveagent
    ulimits:
      nofile: 96000
    depends_on:
      - apache-fpm
  apache-fpm:
    build: ./apache-fpm
    container_name: "apache-fpm"
    restart: unless-stopped
    volumes:
      - app:/var/www/liveagent
      - /etc/geoip:/opt/geoip
      - /var/run/clamav:/var/run/clamav
    ports:
      - 800:800
    cpus: APACHE_CPU_LIMIT
    mem_limit: APACHE_MEM_LIMIT
    ulimits:
      nproc: 30240
      nofile: 65536
volumes:
  app:
    driver: local
